version: 0.1
environment_variables:
    plaintext:
        APP_NAME: "mtm-pwa-front-end"
        S3_BUCKET: "meals-that-matter"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            # - ng build --${BUILD_ENV}
            - npm run build:ssr
            
    post_build:
         commands:
            # - aws s3 cp dist/${APP_NAME} s3://${S3_BUCKET} --recursive
            - aws s3 cp dist/browser s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes