// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XoL2HeK8Y",
    "aws_user_pools_web_client_id": "69sjfo3b8oq82hapcmge34ff6e",
    "oauth": {}
};


export default awsmobile;
