// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lVqDm9q68",
    "aws_user_pools_web_client_id": "1ld51mfch9e1qi946qhn7eg8dr",
    "oauth": {}
};


export default awsmobile;
